#!/bin/sh
# vim: filetype=sh

# Verbose settings thats are nice to have most of the time
alias \
  bat="cat /sys/class/power_supply/BAT?/capacity" \
  cp="cp -iv" \
  ffmpeg="ffmpeg -hide_banner" \
  mkd="mkdir -pv" \
  mv="mv -iv" \
  rm="rm -v"

# Colorize when possible.
alias \
  ccat="highlight --out-format=ansi" \
  diff="diff --color=auto" \
  grep="grep --color=auto" \
  ls="ls -1 --color=auto --group-directories-first"

# Shortcuts
alias \
  D="cd ~/Documents" \
  cf="cd ~/.config" \
  cfa="$EDITOR ~/.config/aliasrc" \
  cfb="$EDITOR ~/.config/bspwm/bspwmrc" \
  cfd="$EDITOR ~/.Xdefaults" \
  cfk="$EDITOR ~/.config/sxhkd/sxhkdrc" \
  cfn="$EDITOR ~/.config/nvim" \
  cfz="$EDITOR $ZDOTDIR/.zshrc" \
  cls="clear" \
  d="cd ~/Downloads" \
  g="git" \
  h="head" \
  ka="killall" \
  l="ls -lah --group-directories-first" \
  p="sudo pacman" \
  sc="cd ~/.local/bin" \
  sdn="sudo shutdown -h now" \
  so="source $ZDOTDIR/.zshrc" \
  t="tail" \
  v="nvim" \
  weath="less -S ~/.local/share/weatherreport" \
  yt="youtube-dl --add-metadata -i" \
  yta="youtube-dl -x -f bestaudio/best"
