#! /bin/sh

# Clear old shortcuts on refresh
bspc rule -r "*"

bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc desktop -f 1

bspc config border_width 2
bspc config window_gap 8
bspc config top_padding 22 
bspc config focus_follows_pointer true

bspc rule -a Zathura state=tiled
bspc config external_rules_command "$(which floaters)"
