#!/bin/sh

# Clear old shortcuts on refresh
bspc rule -r "*"

bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc desktop -f 1

bspc config border_width 1
bspc config border_radius 10
bspc config window_gap 12
bspc config top_padding 26 
bspc config focus_follows_pointer true

bspc rule -a Zathura state=tiled

$HOME/.config/polybar/launch
