#!/bin/env sh

# Kill already running bar if any
killall -q polybar

# Wait for processes to terminate
while pgrep -u $UID -x polybar >/dev/null; do 
  sleep 1; 
done

# Start bar
polybar -r default &
